"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, ClipboardList, KeyRound, ListTodo, PanelsTopLeft, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { Metric, PortalShell } from "@/components/portal-shell";
import { api, errorMessage } from "@/lib/api";
import { formatBytes } from "@/lib/calls";

type Overview = { window: string; metrics: { total: number; success: number; failed: number; rate_limited: number; success_rate: number; p95_duration_ms: number; request_bytes: number; response_bytes: number }; active_key_count: number; expiring_key_count: number; running_task_count: number; retention_days: number; trend: { bucket: string; total: number; success: number }[] };
type Quickstart = { active_key_count: number; published_tool_count: number; published_endpoint_count: number; tools: { slug: string; name: string; description: string; published_endpoint_count: number }[] };
type Call = { request_id: string; tool_slug: string; method: string; path: string; status_code: number; duration_ms: number; created_at: string };

function RetryState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="state-box error"><p>{message}</p><button className="button secondary compact" type="button" onClick={onRetry}>重试</button></div>; }

export default function PortalPage() {
  const [windowValue, setWindowValue] = useState("7d"); const [overview, setOverview] = useState<Overview | null>(null); const [quickstart, setQuickstart] = useState<Quickstart | null>(null); const [calls, setCalls] = useState<Call[] | null>(null);
  const [overviewError, setOverviewError] = useState(""); const [quickError, setQuickError] = useState(""); const [callsError, setCallsError] = useState(""); const [attempt, setAttempt] = useState(0);
  useEffect(() => { setOverview(null); setOverviewError(""); api<Overview>(`/api/me/overview?window=${windowValue}`).then(setOverview).catch((cause) => setOverviewError(errorMessage(cause))); }, [attempt, windowValue]);
  useEffect(() => { setQuickError(""); api<Quickstart>("/api/me/quickstart").then(setQuickstart).catch((cause) => setQuickError(errorMessage(cause))); }, [attempt]);
  useEffect(() => { setCallsError(""); api<Call[]>("/api/me/calls").then(setCalls).catch((cause) => setCallsError(errorMessage(cause))); }, [attempt]);
  const hasKey = Boolean(quickstart?.active_key_count); const hasTools = Boolean(quickstart?.published_tool_count);
  return <PortalShell title="使用概览">
    <div className="overview-heading"><p className="page-intro">确认调用条件、运行指标和需要处理的事项。平台全局 Key 可调用全部已发布接口。</p><div className="overview-refresh"><div className="segmented-control" aria-label="统计时间窗口">{[["24h","24 小时"],["7d","7 天"],["30d","30 天"]].map(([value,label]) => <button key={value} className={windowValue === value ? "active" : ""} onClick={() => setWindowValue(value)}>{label}</button>)}</div><button className="icon-button" title="刷新全部区块" aria-label="刷新全部区块" onClick={() => setAttempt((value) => value + 1)}><RefreshCw size={16} /></button></div></div>
    {overviewError ? <RetryState message={overviewError} onRetry={() => setAttempt((value) => value + 1)} /> : <><div className="metrics"><Metric label="调用量" value={overview ? String(overview.metrics.total) : "-"} caption={`${windowValue} 统计窗口`} /><Metric label="成功率" value={overview ? `${overview.metrics.success_rate}%` : "-"} caption={`失败 ${overview?.metrics.failed ?? "-"} / 限流 ${overview?.metrics.rate_limited ?? "-"}`} tone="green" /><Metric label="P95 延迟" value={overview ? `${overview.metrics.p95_duration_ms} ms` : "-"} caption="端到端 Gateway 延迟" tone="purple" /><Metric label="总流量" value={overview ? formatBytes(overview.metrics.request_bytes + overview.metrics.response_bytes) : "-"} caption="请求与响应脱敏计量" tone="blue" /></div>{overview && <div className="overview-footnote">调用日志实际保留 {overview.retention_days} 天；当前 {overview.active_key_count} 个有效 Key、{overview.expiring_key_count} 个 14 天内到期 Key、{overview.running_task_count} 个运行中任务。</div>}</>}
    <div className="overview-grid"><section className="panel overview-action-panel"><div className="toolbar"><div><h2>接入状态</h2><p className="muted">按顺序处理阻塞项。</p></div></div>{quickError ? <RetryState message={quickError} onRetry={() => setAttempt((value) => value + 1)} /> : !quickstart ? <div className="table-loading-state" role="status">正在加载接入状态...</div> : <><Link className={!hasKey ? "overview-action-row critical" : "overview-action-row"} href="/api-keys">{hasKey ? <CheckCircle2 /> : <CircleAlert />}<span><strong>API 密钥</strong><small>{hasKey ? `已有 ${quickstart.active_key_count} 个有效全局 Key` : "尚无有效 Key，调用会被拒绝"}</small></span><ArrowRight /></Link><Link className={!hasTools ? "overview-action-row critical" : "overview-action-row"} href="/tools">{hasTools ? <CheckCircle2 /> : <CircleAlert />}<span><strong>工具与接口</strong><small>{hasTools ? `${quickstart.published_endpoint_count} 个接口可用` : "管理员尚未发布普通用户接口"}</small></span><ArrowRight /></Link><Link className="overview-action-row" href="/calls"><ClipboardList /><span><strong>调用与排障</strong><small>保留 request_id 以定位一次请求</small></span><ArrowRight /></Link></>}</section><section className="panel overview-alert-panel"><div className="toolbar"><h2>需要关注</h2></div><Link className="overview-alert-row" href="/api-keys"><KeyRound /><span><strong>{overview ? overview.expiring_key_count : "-"} 个 Key 临期</strong><small>提前创建新 Key、切换程序、确认调用后再禁用旧 Key。</small></span></Link><Link className="overview-alert-row" href="/tasks"><ListTodo /><span><strong>{overview ? overview.running_task_count : "-"} 个任务运行中</strong><small>进入任务中心查看状态和工具已配置的能力。</small></span></Link></section></div>
    <section className="panel overview-tools-panel"><div className="toolbar"><div><h2>可用工具</h2><p className="muted">所有工具共用同一个平台 Key。</p></div><Link className="button secondary compact" href="/tools"><PanelsTopLeft size={15} />完整目录</Link></div>{(quickstart?.tools || []).slice(0,5).map((tool) => <Link className="list-row" href={`/tools/${tool.slug}`} key={tool.slug}><span><strong>{tool.name}</strong><small>{tool.description || tool.slug}</small></span><span className="status info">{tool.published_endpoint_count} 个接口</span></Link>)}{quickstart && !quickstart.tools.length && <div className="state-box">暂无可用工具。</div>}</section>
    <section className="panel trend-panel"><div className="toolbar"><div><h2>最近调用</h2><p className="muted">显示最近 5 条，完整筛选和导出请进入调用记录。</p></div><Link className="button secondary compact" href="/calls">全部记录</Link></div>{callsError ? <RetryState message={callsError} onRetry={() => setAttempt((value) => value + 1)} /> : calls === null ? <div className="table-loading-state" role="status">正在加载最近调用...</div> : <div className="call-preview-list">{calls.slice(0,5).map((item) => <div className="call-preview-row" key={item.request_id}><span className={item.status_code >= 400 ? "status warn" : "status good"}>{item.status_code}</span><strong>{item.method} {item.tool_slug}</strong><code>{item.path}</code><span>{item.duration_ms} ms</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}{!calls.length && <div className="state-box">暂无调用记录。</div>}</div>}</section>
  </PortalShell>;
}
